### ISSUE TITLE
IndexOutOfBounds in certain situations.

### ISSUE THREAD

**Issue by SKeeneCode** [Jugen/StyledSegmentTextArea#1]
Firstly, this repository is great, and has been amazing help. I've been rewriting it in kotlin for my project and has been huge fun. Thank you for putting this together @Jugen its really made RichTextFX accessible for me.

I've come across some bugs when testing, and I've verified the same bugs exist in just plain java.

**Bug 1**
Steps to reproduce:
- Create a blank StyledSegmentTextArea (or launch any of the demos and remove the contents).
- Type any letter.
- Press left to move the caret to the very start of the text.
- Press right -> IndexOutOfBounds.

Potential Fix (unsure if has undesired consequences)

[Change this line](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/StyledSegmentTextArea.java#L235) 
`colPos >= pLen-1` to `colPos > pLen-1`

**Bug 2**

- Steps to reproduce.
- Launch the IndentDemo.
- Delete everything.
- Press Enter twice to create an indent:

![image](https://user-images.githubusercontent.com/32420836/107484163-f88ae880-6b79-11eb-8f0e-e194209206a6.png)

- Try and delete the indent -> IndexOutOfBounds

No idea on a fix.

**Comment by SKeeneCode** [comment]
**Bug 3**
Steps to reproduce:

- Launch the IndentDemo
- Press CTRL+A to select everything.
- Press delete -> IndexOutOfBounds

**Comment by SKeeneCode** [comment]
**Bug 4**

Steps to reproduce:
- Launch the IndentDemo
- Place the cursor where the redline is:

![image](https://user-images.githubusercontent.com/32420836/107486061-7b14a780-6b7c-11eb-814d-ed0620b8a9ae.png)

- Click and drag to highlight/select the indent.
- The cursor will become trapped and unable to escape and a Stackoverflow will occur.

**Comment by Jugen** [comment]
Hi @SKeeneCode glad this has helped you and thank you for reporting the issues above, I have submitted a PR that addresses all of them.

Note that IndentSegment was an experimental feature that arose out of [RichTextFX #840](https://github.com/FXMisc/RichTextFX/issues/840), and I'm not confident that it is actually the way this feature should be added. That being said I do use the StyledSegmentTextArea in my production code for displaying LabelSegments.

**Comment by SKeeneCode** [comment]
Thanks for the quick fix! Unfortunately I did find another :) If you place the caret on an empty line, press enter -> delete -> enter -> delete -> IndexOutOfBounds

I thought the indents might make a good base to implement bullet point lists. However I see that there is an implementation of bullet point lists in the rich text demo so I'll have a look at that.

**Comment by tchudyk** [comment]
Hi, I'm not sure but maybe my last fix solved this issue too - https://github.com/FXMisc/Flowless/pull/92 - I had also problems with `IndexOutOfBoundsException`.
